package one.globalconnect.paymentapp.uicpos.pos.model

data class TransLog(
    /* transaction request */
    var TxnType: String = "",        // HOST_TRANS_SALE, HOST_TRANS_VOID, etc.
    var AccType: String = "Default", // Account Type
    var AcquirerId: String = "",
    var IssuerId: String = "",
    var CardRangeId: String = "",
    var CardRangeName: String = "",
    var CurrCode: String = "",
    var TxnAmt: String = "",
    var PartialApprovalOriginalAmount: String = "",
    var CashbackAmt: String = "",
    var BaseAmt: String = "",
    var Tax1Amt: String = "",
    var Tax1DiscountAmt: String = "",
    var OriginalTax1Amt: String = "",
    var Tax2Amt: String = "",
    var TipAmt: String = "",
    var PaymentPlan: String = "",
    var ForceOnline: String = "",
    var TxnId: String? = "",
    var OriginalMessageType: String? = "",
    var OriginalStan: String? = "",
    var MessageTypeOverride: String? = null,
    var ProcessingCodeOverride: String? = null,
    var InvoiceId: String = "",
    var AuthNtwkName: String = "",
    var CardDataSource: String = "",
    var CardNbr: String = "",
    var MaskedCardNbr: String = "",
    var HashedCardNbr: String = "",
    var ExpireMonth: String = "",
    var ExpireYear: String = "",
    var CVV: String = "",
    var AuthCode: String? = "",
    var AuthTimeStamp: String? = "",
    var Token: String? = "",
    var Address: String? = "",
    var Telephone: String? = "",
    var ZIP: String? = "",

    /* transaction response */
    var RspDT: String? = "",
    var RspText: String? = "",
    var RspCode: String? = "",
    var TxnResult: String? = "",
    var TxnResultMsg: String? = "",
    var RefNbr: String? = "",
    var ExternalRefNumber: String? = "",
    var AlternateHostResponse: String? = "",
    var AdditionalHostPrintData: String? = "",
    var PaymentPlanQueryResponse: String? = "",
    var AuthorizationId: String? = "",
    var LoyaltyBalancePoints: String? = "",
    var CardType: String? = "",
    var AppName: String? = "",
    var AppId: String? = "",
    var AID: String? = "",
    var AppLabel: String? = "",
    var PAN: String? = "",
    var CVMResult: String? = "",
    var CVMText: String? = "",
    var TVR: String? = "",
    var TSI: String? = "",
    var AC: String? = "",
    var ATC: String? = "",
    var ARC: String? = "",
    var IAD: String? = "",
    var CryptoInfo: String? = "",
    var Cryptogram: String? = "",
    var Field55: String? = "",
    var TxnInterface: String? = "",
    var CardhdrName: String? = "",
    var Track1: String? = "",
    var Track2: String? = "",
    var Track3: String? = "",
    @Transient var PINBlock: String? = "",
    @Transient var KSN: String? = "",

    // Settle
    var BatchId: String? = "",
    var TxnCnt: String? = "",
    var TotalAmt: String? = "",
    var BatchSeqNbr: String? = "",
    var SettlementTotals: ReconciliationTotals? = null,

    var HealthCare: HealthCare = HealthCare(),

    var CVMResultStatus: Int = 0,
    var FolioNumber: String? = "",
    var OriginalTransactionId: String? = "",
    var TipProcessingInfo: String? = "",
    var SignatureRequired: Boolean = false,
    var SignatureCaptured: Boolean = false,
)
